model:
  type: GRU
  feat_dim: 128
  num_layers: 2
  dropout: 0.2

train:
  batch_size: 64
  seed: 114514
  max_iters: 10_000
  val_freq: 64
  val_num: 20
  optimizer:
    type: adam
    lr: 1.e-2
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999